import Link from 'next/link';

import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import ProvidersList from './_components/providersList';
import ProvidersDivider from './_components/divider';
import { EmailProviderLoginForm } from './_components/emailProviderLoginForm';
import { Suspense } from 'react';
import { env } from '@/env';

export const dynamic = 'force-dynamic'
export const metadata = {
	title: `Login - ${env.APP_NAME}`,
	description: 'Generated by create-t3-app',
	icons: [{ rel: 'icon', url: '/favicon.ico' }]
};

export default function LoginForm() {
	return (
		<div className='flex min-h-screen items-center justify-center'>
			<Card className="w-full max-w-sm">
			<CardHeader>
				<CardTitle className='text-2xl'>Login</CardTitle>
				<CardDescription>Enter your email below to login to your account</CardDescription>
			</CardHeader>
			<CardContent className='space-y-8'>
				{/* Form to login with Email one time link */}
				<Suspense fallback={<div>Loading...</div>}>
					<EmailProviderLoginForm />
				</Suspense>

				{/* Divider between Email and other providers login forms. */}
				<ProvidersDivider />

				{/* Login with other providers (client-rendered) */}
				<ProvidersList />
				<div className='mt-4 text-center text-sm'>
					Don&apos;t have an account?{' '}
					<Link
						href='#'
						className='underline'>
						Sign up
					</Link>
				</div>
			</CardContent>
			</Card>
		</div>
	);
}
