import { ChartLine } from 'lucide-react';
import { headers } from 'next/headers';
import { redirect } from 'next/navigation';
import { env } from '@/env';
import { auth } from '@/lib/auth';
import { LoginForm } from './_components/login-form';

export const dynamic = 'force-dynamic';
export const metadata = {
	description: 'Generated by create-t3-app',
	icons: [{ rel: 'icon', url: '/favicon.ico' }],
	title: `Login - ${env.APP_NAME}`
};

export default async function LoginPage({
	searchParams
}: {
	searchParams: Promise<Record<string, string | string[] | undefined>>;
}) {
	const session = await auth.api.getSession({ headers: await headers() });

	if (session?.user) redirect('/portfolio');
	const sp = await searchParams;

	return (
		<div className='flex min-h-svh flex-col items-center justify-center gap-6 p-6 md:p-10'>
			<div className='flex w-full max-w-sm flex-col gap-6'>
				<a className='flex items-center gap-2 self-center font-medium' href='/'>
					<span className='grid size-9 place-items-center rounded-md bg-primary/10 text-primary'>
						<ChartLine className='size-5' />
					</span>
					{env.APP_NAME}
				</a>
				<LoginForm errorCode={Array.isArray(sp?.error) ? sp?.error?.[0] : sp?.error} />
			</div>
		</div>
	);
}
